[workspace]
resolver = "3"
members = [
    "chapters/ch02_text_processing"
]

[workspace.package]
name = "crab-llm-scratch"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
regex = "1.12.2"
